# Generated by Django 4.0.5 on 2022-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
