# Generated by Django 4.0.5 on 2022-07-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_count_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_sold',
        ),
    ]
