# Generated by Django 4.0.5 on 2022-07-15 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0002_couponuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponUser',
            new_name='CouponUsers',
        ),
    ]
