# Generated by Django 4.0.5 on 2022-07-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_email',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
