# Generated by Django 4.0.5 on 2022-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
    ]
