# Generated by Django 4.0.5 on 2022-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_main_category_count_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='count_sold',
            field=models.IntegerField(default=0),
        ),
    ]
