# Generated by Django 4.0.5 on 2022-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_sum',
            field=models.FloatField(default=0),
        ),
    ]
